# Copyright 2015 Oliver Cope
# Copyright 2026 Sergey Variasov
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Oracle backend implemented with the ``oracledb`` driver."""

from datetime import datetime, timezone
from typing import Any

import oracledb
from classic.migrations.backends.base import Backend, lock_hash
from classic.migrations.exceptions import MigrationLockError


def _utcnow() -> datetime:
    """Return the current UTC time as a naive ``datetime``."""
    return datetime.now(timezone.utc).replace(tzinfo=None)


class _OracleCursor:
    """Wrap an ``oracledb`` cursor to strip a trailing SQL terminator.

    The thin-mode ``oracledb`` driver rejects statements that end in a
    semicolon (``ORA-00922``), while migration/hook statements read from
    ``.sql`` files retain their trailing terminator.
    """

    def __init__(self, cursor: Any) -> None:
        self._cursor = cursor

    def execute(self, sql: str, params: Any = None) -> Any:
        """Execute ``sql``, stripping a trailing terminator for plain SQL.

        The thin-mode ``oracledb`` driver rejects ordinary statements that
        end in a semicolon (``ORA-00922``), but PL/SQL blocks require their
        terminating semicolon.
        """
        stripped = sql.rstrip().rstrip(";").rstrip()
        head = stripped.lstrip().lower()
        if head.startswith(("begin", "declare")):
            statement = stripped + ";"
        else:
            statement = stripped
        if params is None:
            return self._cursor.execute(statement)
        return self._cursor.execute(statement, params)

    def __getattr__(self, name: str) -> Any:
        return getattr(self._cursor, name)


class OracleBackend(Backend, driver=oracledb):
    """Oracle migration backend using the ``oracledb`` driver (thin mode)."""

    supports_schemas = True

    def connect(self) -> oracledb.Connection:
        """Open an Oracle connection using the ``oracledb`` driver."""
        kwargs: dict[str, Any] = {}
        if self.db_host is not None:
            kwargs["host"] = self.db_host
        if self.db_port is not None:
            kwargs["port"] = int(self.db_port)
        if self.db_name is not None:
            kwargs["service_name"] = self.db_name
        if self.db_user is not None:
            kwargs["user"] = self.db_user
        if self.db_password is not None:
            kwargs["password"] = self.db_password
        kwargs.update(self.db_args)
        return self.driver.connect(**kwargs)

    def cursor(self) -> Any:
        """Return a cursor that tolerates a trailing SQL terminator."""
        return _OracleCursor(self.connection.cursor())

    def list_tables(self) -> list[str]:
        """Return the names of tables in the migration schema (owner)."""
        if self.migration_schema:
            owner = self.migration_schema.upper()
            cursor = self.execute(
                "SELECT table_name FROM all_tables WHERE owner = :owner",
                {"owner": owner},
            )
        else:
            cursor = self.execute("SELECT table_name FROM user_tables")
        return [row[0] for row in cursor.fetchall()]

    def _create_migration_table(self) -> None:
        self.execute(
            f"CREATE TABLE {self.migration_table_quoted} ("
            "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "migration_id VARCHAR2(255) NOT NULL, "
            "created_at TIMESTAMP NOT NULL, "
            "status VARCHAR2(16) NOT NULL)",
        )

    def _copy_versions(self) -> None:
        self.execute(
            "INSERT INTO "
            f"{self.migration_table_quoted} (migration_id, created_at, status) "
            "SELECT migration_id, applied_at_utc, 'APPLIED' "
            f"FROM {self.versions_table_quoted}",
        )

    def _migration_history(self) -> list[tuple[Any, ...]]:
        cursor = self.execute(
            "SELECT migration_id, created_at, status "
            f"FROM {self.migration_table_quoted} ORDER BY id",
        )
        return [tuple(row) for row in cursor.fetchall()]

    def mark(self, migration_id: str, status: str) -> None:
        """Append a migration history event."""
        self.execute(
            "INSERT INTO "
            f"{self.migration_table_quoted} (migration_id, created_at, status) "
            "VALUES (:migration_id, :created_at, :status)",
            {
                "migration_id": migration_id,
                "created_at": _utcnow(),
                "status": status,
            },
        )

    def acquire_lock(self) -> None:
        """Acquire an Oracle named advisory lock via ``DBMS_LOCK.REQUEST``."""
        lock_id = lock_hash(self.migration_table) & 0x3FFFFFFF
        cursor = self.execute(
            "SELECT DBMS_LOCK.REQUEST(:1, :2, :3) FROM dual",
            (lock_id, 6, 0),
        )
        result = cursor.fetchone()[0]
        if result != 0:
            raise MigrationLockError(
                "Could not acquire advisory lock on the database",
            )

    def release_lock(self) -> None:
        """Release the Oracle named advisory lock."""
        lock_id = lock_hash(self.migration_table) & 0x3FFFFFFF
        self.execute("SELECT DBMS_LOCK.RELEASE(:1) FROM dual", (lock_id,))

    def begin(self) -> None:
        """Begin an implicit transaction (no SQL required in Oracle)."""
        self._in_transaction = True

    def commit(self) -> None:
        """Commit the current transaction."""
        self.connection.commit()
        self._in_transaction = False

    def rollback(self) -> None:
        """Rollback the current transaction."""
        self.connection.rollback()
        self._in_transaction = False
