WHENEVER SQLERROR CONTINUE

ALTER SESSION SET CONTAINER = FREEPDB1;
GRANT EXECUTE ON SYS.DBMS_LOCK TO test;

ALTER SESSION SET CONTAINER = test;
GRANT EXECUTE ON SYS.DBMS_LOCK TO test;

ALTER SESSION SET CONTAINER = CDB$ROOT;
